# Generated by Django 5.0.7 on 2024-08-03 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=200)),
                ('preparation_time', models.DurationField()),
                ('ingredient_list', models.JSONField()),
                ('number_of_servings', models.IntegerField()),
                ('procedure', models.TextField()),
                ('nutritional_guide', models.TextField()),
                ('skills_needed', models.CharField(max_length=200)),
                ('age_range_that_can_eat', models.JSONField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dish_image', models.ImageField(upload_to='dish_images/')),
            ],
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('family_size', models.IntegerField()),
                ('age_range', models.JSONField()),
                ('meal_preference', models.JSONField()),
                ('allergies', models.JSONField()),
                ('cooking_skills', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DishPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=100)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kusinaiapp.dish')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kusinaiapp.appuser')),
            ],
            options={
                'unique_together': {('user', 'dish')},
            },
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kusinaiapp.dish')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kusinaiapp.appuser')),
            ],
            options={
                'unique_together': {('user', 'dish')},
            },
        ),
    ]
